# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.human_property_model_kms import KMSHumanPropertyModel


class HumanPropertyModel(Model, KMSHumanPropertyModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, unit: str = None, writable: bool = None):  # noqa: E501
        """HumanPropertyModel - a model defined in Swagger

        :param unit: The unit of this HumanPropertyModel.  # noqa: E501
        :type unit: str
        :param writable: The writable of this HumanPropertyModel.  # noqa: E501
        :type writable: bool
        """
        self.swagger_types = {
            'unit': str,
            'writable': bool
        }
        
        self.attribute_map = {
            'unit': 'unit',
            'writable': 'writable'
        }
        self._unit = unit
        self._writable = writable
    
    @classmethod
    def from_dict(cls, dikt) -> 'HumanPropertyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HumanPropertyModel of this HumanPropertyModel.  # noqa: E501
        :rtype: HumanPropertyModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def unit(self) -> str:
        """Gets the unit of this HumanPropertyModel.


        :return: The unit of this HumanPropertyModel.
        :rtype: str
        """
        return self._unit
    
    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this HumanPropertyModel.


        :param unit: The unit of this HumanPropertyModel.
        :type unit: str
        """
        
        self._unit = unit
    
    @property
    def writable(self) -> bool:
        """Gets the writable of this HumanPropertyModel.


        :return: The writable of this HumanPropertyModel.
        :rtype: bool
        """
        return self._writable
    
    @writable.setter
    def writable(self, writable: bool):
        """Sets the writable of this HumanPropertyModel.


        :param writable: The writable of this HumanPropertyModel.
        :type writable: bool
        """
        
        self._writable = writable
