# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.load_balancer_model_kms import LoadBalancerModelKMS


class LoadBalancerModel(Model, LoadBalancerModelKMS):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, id: str = None, timestamp: int = None):  # noqa: E501
        """LoadBalancerModel - a model defined in Swagger

        :param id: The id of this LoadBalancerModel.  # noqa: E501
        :type id: str
        :param timestamp: The timestamp of this LoadBalancerModel.  # noqa: E501
        :type timestamp: int
        """
        self.swagger_types = {
            'id': str,
            'timestamp': int
        }
        
        self.attribute_map = {
            'id': '_id',
            'timestamp': 'timestamp'
        }
        self._id = id
        self._timestamp = timestamp
    
    @classmethod
    def from_dict(cls, dikt) -> 'LoadBalancerModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoadBalancerModel of this LoadBalancerModel.  # noqa: E501
        :rtype: LoadBalancerModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def id(self) -> str:
        """Gets the id of this LoadBalancerModel.


        :return: The id of this LoadBalancerModel.
        :rtype: str
        """
        return self._id
    
    @id.setter
    def id(self, id: str):
        """Sets the id of this LoadBalancerModel.


        :param id: The id of this LoadBalancerModel.
        :type id: str
        """
        
        self._id = id
    
    @property
    def timestamp(self) -> int:
        """Gets the timestamp of this LoadBalancerModel.


        :return: The timestamp of this LoadBalancerModel.
        :rtype: int
        """
        return self._timestamp
    
    @timestamp.setter
    def timestamp(self, timestamp: int):
        """Sets the timestamp of this LoadBalancerModel.


        :param timestamp: The timestamp of this LoadBalancerModel.
        :type timestamp: int
        """
        
        self._timestamp = timestamp
