# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.production_info_string_item_kms import KMSProductionInfoStringItem


class ProductionInfoStringItem(Model, KMSProductionInfoStringItem):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, name: str = None, value: str = None):  # noqa: E501
        """ProductionInfoStringItem - a model defined in Swagger

        :param name: The name of this ProductionInfoStringItem.  # noqa: E501
        :type name: str
        :param value: The value of this ProductionInfoStringItem.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'name': str,
            'value': str
        }
        
        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }
        self._name = name
        self._value = value
    
    @classmethod
    def from_dict(cls, dikt) -> 'ProductionInfoStringItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductionInfoStringItem of this ProductionInfoStringItem.  # noqa: E501
        :rtype: ProductionInfoStringItem
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def name(self) -> str:
        """Gets the name of this ProductionInfoStringItem.


        :return: The name of this ProductionInfoStringItem.
        :rtype: str
        """
        return self._name
    
    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductionInfoStringItem.


        :param name: The name of this ProductionInfoStringItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        
        self._name = name
    
    @property
    def value(self) -> str:
        """Gets the value of this ProductionInfoStringItem.


        :return: The value of this ProductionInfoStringItem.
        :rtype: str
        """
        return self._value
    
    @value.setter
    def value(self, value: str):
        """Sets the value of this ProductionInfoStringItem.


        :param value: The value of this ProductionInfoStringItem.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        
        self._value = value
