# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.skill_property_model_kms import KMSSkillPropertyModel


class SkillPropertyModel(Model, KMSSkillPropertyModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, writable: bool = None):  # noqa: E501
        """SkillPropertyModel - a model defined in Swagger

        :param writable: The writable of this SkillPropertyModel.  # noqa: E501
        :type writable: bool
        """
        self.swagger_types = {
            'writable': bool
        }
        
        self.attribute_map = {
            'writable': 'writable'
        }
        self._writable = writable
    
    @classmethod
    def from_dict(cls, dikt) -> 'SkillPropertyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SkillPropertyModel of this SkillPropertyModel.  # noqa: E501
        :rtype: SkillPropertyModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def writable(self) -> bool:
        """Gets the writable of this SkillPropertyModel.


        :return: The writable of this SkillPropertyModel.
        :rtype: bool
        """
        return self._writable
    
    @writable.setter
    def writable(self, writable: bool):
        """Sets the writable of this SkillPropertyModel.


        :param writable: The writable of this SkillPropertyModel.
        :type writable: bool
        """
        if writable is None:
            raise ValueError("Invalid value for `writable`, must not be `None`")  # noqa: E501
        
        self._writable = writable
