# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.value_property_model_kms import KMSValuePropertyModel


class ValuePropertyModel(Model, KMSValuePropertyModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self):  # noqa: E501
        """ValuePropertyModel - a model defined in Swagger

        """
        self.swagger_types = {
        }
        
        self.attribute_map = {
        }
    
    @classmethod
    def from_dict(cls, dikt) -> 'ValuePropertyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValuePropertyModel of this ValuePropertyModel.  # noqa: E501
        :rtype: ValuePropertyModel
        """
        return util.deserialize_model(dikt, cls)
