# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.constraint_model_kms import KMSConstraintModel


class ConstraintModel(Model, KMSConstraintModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self):  # noqa: E501
        """ConstraintModel - a model defined in Swagger

        """
        self.swagger_types = {
        }
        
        self.attribute_map = {
        }
    
    @classmethod
    def from_dict(cls, dikt) -> 'ConstraintModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConstraintModel of this ConstraintModel.  # noqa: E501
        :rtype: ConstraintModel
        """
        return util.deserialize_model(dikt, cls)
