# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.number_property_model_kms import KMSNumberPropertyModel


class NumberPropertyModel(Model, KMSNumberPropertyModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, key: str = None, writable: bool = None, kafka_topic: str = None, uuid: str = None,
                 timestamp: int = None, value: float = None, type: str = None, min: float = None,
                 max: float = None):  # noqa: E501
        """NumberPropertyModel - a model defined in Swagger

        :param key: The key of this NumberPropertyModel.  # noqa: E501
        :type key: str
        :param writable: The writable of this NumberPropertyModel.  # noqa: E501
        :type writable: bool
        :param kafka_topic: The kafka_topic of this NumberPropertyModel.  # noqa: E501
        :type kafka_topic: str
        :param uuid: The uuid of this NumberPropertyModel.  # noqa: E501
        :type uuid: str
        :param timestamp: The timestamp of this NumberPropertyModel.  # noqa: E501
        :type timestamp: int
        :param value: The value of this NumberPropertyModel.  # noqa: E501
        :type value: float
        :param type: The type of this NumberPropertyModel.  # noqa: E501
        :type type: str
        :param min: The min of this NumberPropertyModel.  # noqa: E501
        :type min: float
        :param max: The max of this NumberPropertyModel.  # noqa: E501
        :type max: float
        """
        self.swagger_types = {
            'key': str,
            'writable': bool,
            'kafka_topic': str,
            'uuid': str,
            'timestamp': int,
            'value': float,
            'type': str,
            'min': float,
            'max': float
        }
        
        self.attribute_map = {
            'key': 'key',
            'writable': 'writable',
            'kafka_topic': 'kafka_topic',
            'uuid': 'uuid',
            'timestamp': 'timestamp',
            'value': 'value',
            'type': 'type',
            'min': 'min',
            'max': 'max'
        }
        self._key = key
        self._writable = writable
        self._kafka_topic = kafka_topic
        self._uuid = uuid
        self._timestamp = timestamp
        self._value = value
        self._type = type
        self._min = min
        self._max = max
    
    @classmethod
    def from_dict(cls, dikt) -> 'NumberPropertyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NumberPropertyModel of this NumberPropertyModel.  # noqa: E501
        :rtype: NumberPropertyModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def key(self) -> str:
        """Gets the key of this NumberPropertyModel.


        :return: The key of this NumberPropertyModel.
        :rtype: str
        """
        return self._key
    
    @key.setter
    def key(self, key: str):
        """Sets the key of this NumberPropertyModel.


        :param key: The key of this NumberPropertyModel.
        :type key: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501
        
        self._key = key
    
    @property
    def writable(self) -> bool:
        """Gets the writable of this NumberPropertyModel.


        :return: The writable of this NumberPropertyModel.
        :rtype: bool
        """
        return self._writable
    
    @writable.setter
    def writable(self, writable: bool):
        """Sets the writable of this NumberPropertyModel.


        :param writable: The writable of this NumberPropertyModel.
        :type writable: bool
        """
        
        self._writable = writable
    
    @property
    def kafka_topic(self) -> str:
        """Gets the kafka_topic of this NumberPropertyModel.


        :return: The kafka_topic of this NumberPropertyModel.
        :rtype: str
        """
        return self._kafka_topic
    
    @kafka_topic.setter
    def kafka_topic(self, kafka_topic: str):
        """Sets the kafka_topic of this NumberPropertyModel.


        :param kafka_topic: The kafka_topic of this NumberPropertyModel.
        :type kafka_topic: str
        """
        
        self._kafka_topic = kafka_topic
    
    @property
    def uuid(self) -> str:
        """Gets the uuid of this NumberPropertyModel.


        :return: The uuid of this NumberPropertyModel.
        :rtype: str
        """
        return self._uuid
    
    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this NumberPropertyModel.


        :param uuid: The uuid of this NumberPropertyModel.
        :type uuid: str
        """
        
        self._uuid = uuid
    
    @property
    def timestamp(self) -> int:
        """Gets the timestamp of this NumberPropertyModel.


        :return: The timestamp of this NumberPropertyModel.
        :rtype: int
        """
        return self._timestamp
    
    @timestamp.setter
    def timestamp(self, timestamp: int):
        """Sets the timestamp of this NumberPropertyModel.


        :param timestamp: The timestamp of this NumberPropertyModel.
        :type timestamp: int
        """
        
        self._timestamp = timestamp
    
    @property
    def value(self) -> float:
        """Gets the value of this NumberPropertyModel.


        :return: The value of this NumberPropertyModel.
        :rtype: float
        """
        return self._value
    
    @value.setter
    def value(self, value: float):
        """Sets the value of this NumberPropertyModel.


        :param value: The value of this NumberPropertyModel.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        
        self._value = value
    
    @property
    def type(self) -> str:
        """Gets the type of this NumberPropertyModel.


        :return: The type of this NumberPropertyModel.
        :rtype: str
        """
        return self._type
    
    @type.setter
    def type(self, type: str):
        """Sets the type of this NumberPropertyModel.


        :param type: The type of this NumberPropertyModel.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        
        self._type = type
    
    @property
    def min(self) -> float:
        """Gets the min of this NumberPropertyModel.


        :return: The min of this NumberPropertyModel.
        :rtype: float
        """
        return self._min
    
    @min.setter
    def min(self, min: float):
        """Sets the min of this NumberPropertyModel.


        :param min: The min of this NumberPropertyModel.
        :type min: float
        """
        
        self._min = min
    
    @property
    def max(self) -> float:
        """Gets the max of this NumberPropertyModel.


        :return: The max of this NumberPropertyModel.
        :rtype: float
        """
        return self._max
    
    @max.setter
    def max(self, max: float):
        """Sets the max of this NumberPropertyModel.


        :param max: The max of this NumberPropertyModel.
        :type max: float
        """
        
        self._max = max
