# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.task_property_model_kms import KMSTaskPropertyModel


class TaskPropertyModel(Model, KMSTaskPropertyModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, writable: bool = None):  # noqa: E501
        """TaskPropertyModel - a model defined in Swagger

        :param writable: The writable of this TaskPropertyModel.  # noqa: E501
        :type writable: bool
        """
        self.swagger_types = {
            'writable': bool
        }
        
        self.attribute_map = {
            'writable': 'writable'
        }
        self._writable = writable
    
    @classmethod
    def from_dict(cls, dikt) -> 'TaskPropertyModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskPropertyModel of this TaskPropertyModel.  # noqa: E501
        :rtype: TaskPropertyModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def writable(self) -> bool:
        """Gets the writable of this TaskPropertyModel.


        :return: The writable of this TaskPropertyModel.
        :rtype: bool
        """
        return self._writable
    
    @writable.setter
    def writable(self, writable: bool):
        """Sets the writable of this TaskPropertyModel.


        :param writable: The writable of this TaskPropertyModel.
        :type writable: bool
        """
        
        self._writable = writable
