# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model


class BaseProductInfoItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, name: str = None):  # noqa: E501
        """BaseProductInfoItem - a model defined in Swagger

        :param name: The name of this BaseProductInfoItem.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'name': str
        }
        
        self.attribute_map = {
            'name': 'name'
        }
        self._name = name
    
    @classmethod
    def from_dict(cls, dikt) -> 'BaseProductInfoItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseProductInfoItem of this BaseProductInfoItem.  # noqa: E501
        :rtype: BaseProductInfoItem
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def name(self) -> str:
        """Gets the name of this BaseProductInfoItem.


        :return: The name of this BaseProductInfoItem.
        :rtype: str
        """
        return self._name
    
    @name.setter
    def name(self, name: str):
        """Sets the name of this BaseProductInfoItem.


        :param name: The name of this BaseProductInfoItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        
        self._name = name
