# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model


class BaseModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, objectType: str = None, name: str = None, uuid: str = None, kafka_topic: str = None,
                 id: str = None):  # noqa: E501
        """BaseModel - a model defined in Swagger

        :param objectType: The objectType of this BaseModel.  # noqa: E501
        :type objectType: str
        :param name: The name of this BaseModel.  # noqa: E501
        :type name: str
        :param uuid: The uuid of this BaseModel.  # noqa: E501
        :type uuid: str
        :param kafka_topic: The kafka_topic of this BaseModel.  # noqa: E501
        :type kafka_topic: str
        :param id: The id of this BaseModel.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'objectType': str,
            'name': str,
            'uuid': str,
            'kafka_topic': str,
            'id': str
        }
        
        self.attribute_map = {
            'objectType': 'objectType',
            'name': 'name',
            'uuid': 'uuid',
            'kafka_topic': 'kafka_topic',
            'id': 'id'
        }
        self._objectType = objectType
        self._name = name
        self._uuid = uuid
        self._kafka_topic = kafka_topic
        self._id = id
    
    @classmethod
    def from_dict(cls, dikt) -> 'BaseModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseModel of this BaseModel.  # noqa: E501
        :rtype: BaseModel
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def objectType(self) -> str:
        """Gets the objectType of this BaseModel.


        :return: The objectType of this BaseModel.
        :rtype: str
        """
        return self._objectType
    
    @objectType.setter
    def objectType(self, objectType: str):
        """Sets the objectType of this BaseModel.


        :param objectType: The objectType of this BaseModel.
        :type objectType: str
        """
        allowed_values = ["actuator", "sensor", "human", "service", "skill", "task", "action", "healthdata",
                          "humanrole", "message", "permission", "preference", "property"]  # noqa: E501
        if objectType not in allowed_values:
            raise ValueError(
                "Invalid value for `objectType` ({0}), must be one of {1}"
                    .format(objectType, allowed_values)
            )
        
        self._objectType = objectType
    
    @property
    def name(self) -> str:
        """Gets the name of this BaseModel.

        []  # noqa: E501

        :return: The name of this BaseModel.
        :rtype: str
        """
        return self._name
    
    @name.setter
    def name(self, name: str):
        """Sets the name of this BaseModel.

        []  # noqa: E501

        :param name: The name of this BaseModel.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        
        self._name = name
    
    @property
    def uuid(self) -> str:
        """Gets the uuid of this BaseModel.

        []  # noqa: E501

        :return: The uuid of this BaseModel.
        :rtype: str
        """
        return self._uuid
    
    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this BaseModel.

        []  # noqa: E501

        :param uuid: The uuid of this BaseModel.
        :type uuid: str
        """
        
        self._uuid = uuid
    
    @property
    def kafka_topic(self) -> str:
        """Gets the kafka_topic of this BaseModel.

        []  # noqa: E501

        :return: The kafka_topic of this BaseModel.
        :rtype: str
        """
        return self._kafka_topic
    
    @kafka_topic.setter
    def kafka_topic(self, kafka_topic: str):
        """Sets the kafka_topic of this BaseModel.

        []  # noqa: E501

        :param kafka_topic: The kafka_topic of this BaseModel.
        :type kafka_topic: str
        """
        
        self._kafka_topic = kafka_topic
    
    @property
    def id(self) -> str:
        """Gets the id of this BaseModel.

        []  # noqa: E501

        :return: The id of this BaseModel.
        :rtype: str
        """
        return self._id
    
    @id.setter
    def id(self, id: str):
        """Sets the id of this BaseModel.

        []  # noqa: E501
        
        :param id: The id of this BaseModel.
        :type id: str
        """
        
        self._id = id
