# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, ci_testing ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose  up -d
          docker ps
          echo sleeping for 20 seconds
          sleep 20


      - name: Postman Tests
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 3236604-3a3f4468-72c9-4954-9b9b-eb8bcd9e7aff
          environment: 3236604-018e98e3-a6e3-4f90-be98-3bb3a8515092


      - name: Docker Log
        run: |
          docker logs chariot-kms_flask_1



